version: '3'
services:
  portfolio-web:
    image: asia.gcr.io/portfolio-383520/portfolio/web
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"