name: Build and push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
      GCR_PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
      GCR_HOSTNAME: ${{ secrets.GCR_HOSTNAME }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: $SERVICE_ACCOUNT_KEY
        project_id: $GCR_PROJECT_ID
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1.1.0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    # - uses: google-github-actions/setup-gcloud@v1.1.0
    #   with:
    #     service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    #     project_id: ${{ env.GCR_PROJECT_ID }}
    #     export_default_credentials: true

    # - name: Build Docker Image
    #   run: docker build -t $IMAGE_NAME:latest .

    # - name: Automatic Tagging of Releases
    #   id: increment-git-tag
    #   run: |
    #     bash ./scripts/git_update.sh -v major
    # - name: Login to gcloud
    #   run: gcloud auth login
    # - name: Configure Docker Client
    #   run: |-
    #     gcloud auth configure-docker --quiet
    #     gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
    # - name: Push Docker Image to Container Registry (GCR)
    #   env:
    #     GIT_TAG: v0.1.0
    #     # GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
    #   run: |-
    #     docker tag $IMAGE_NAME:latest $GCR_HOSTNAME/$GCR_PROJECT_ID/$IMAGE_NAME:latest
    #     docker tag $IMAGE_NAME:latest $GCR_HOSTNAME/$GCR_PROJECT_ID/$IMAGE_NAME:$GIT_TAG
    #     docker push $GCR_HOSTNAME/$GCR_PROJECT_ID/$IMAGE_NAME:latest
    #     docker push $GCR_HOSTNAME/$GCR_PROJECT_ID/$IMAGE_NAME:$GIT_TAG
    # - name: Push Docker Image to Artifact Registry
    #   env:
    #     GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
    #   run: |-
    #     docker tag $IMAGE_NAME:latest asia-southeast2-docker.pkg.dev/$GCR_PROJECT_ID/images/$IMAGE_NAME:latest
    #     docker tag $IMAGE_NAME:latest asia-southeast2-docker.pkg.dev/$GCR_PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
    #     docker push asia-southeast2-docker.pkg.dev/$GCR_PROJECT_ID/images/$IMAGE_NAME:latest
    #     docker push asia-southeast2-docker.pkg.dev/$GCR_PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
